### ISSUE TITLE
GemeindeCSV splitten pro Abstimmung

### ISSUE THREAD

**Issue by UniDomi** [UniDomi/dataVis_tgPoll#1]
Herausfinden warum der Datensatz nicht stimmt.

**Comment by maerlae** [comment]
Wahrscheinlich könnten wir anstatt das csv splitten die Daten filtern (ging bei mir mit den files der Indikatoren, z.B nach Jahr und dann für eine Gemeinde filtern), aber wie dann der Wechsel eingebaut wird ist noch nicht klar.

**Comment by UniDomi** [comment]
habe ich mir auch schon überlegt, zumal das splitten etwas länger dauert als gedacht. Ich werde versuchen ob ich einfach die IDs nehmen kann und jeweils diese auslese
